version: '3.3'

services:
  chatgpt-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    environment:
      - OPENAI_EMAIL=${OPENAI_EMAIL}
      - OPENAI_PASSWORD=${OPENAI_PASSWORD}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
